controller_manager:
  ros__parameters:
    update_rate: 125  # Hz

    Arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


Arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - Arm_joint1
      - Arm_joint2
      - Arm_joint3
      - Arm_joint4
      - Arm_joint5
      - Arm_joint6
    allow_nonzero_velocity_at_trajectory_end: true
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
          stopped_velocity_tolerance: 0.02
          goal_time: 1.0
          Arm_joint1:
            trajectory: 0.3
            goal: 0.01
          Arm_joint2:
            trajectory: 0.3
            goal: 0.01
          Arm_joint3:
            trajectory: 0.3
            goal: 0.01
          Arm_joint4:
            trajectory: 0.3
            goal: 0.01
          Arm_joint5:
            trajectory: 0.3
            goal: 0.01
          Arm_joint6:
            trajectory: 0.3
            goal: 0.01