# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Arm_joint1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 6.0
  Arm_joint2:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 8.0
  Arm_joint3:
    has_velocity_limits: true
    max_velocity: 1.0  # Reduced from 2.0 to minimize backlash effects
    has_acceleration_limits: true
    max_acceleration: 4.0  # Reduced from 8.0 to minimize backlash effects
  Arm_joint4:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 10.0
  Arm_joint5:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 10.0
  Arm_joint6:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 10.0
